apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    name: MyApp
    environment: prod
spec:
  containers:
  - name: myapp-container
    image: kpavan2004/titanic-api-demo
    ports:
      - containerPort: 8001