apiVersion: v1
kind: Service
metadata:
  name: my-svc
spec:
  type: NodePort
  selector:
    name: MyApp
    environment: prod
  ports:
  - port: 5000        # Service IP Port
    targetPort: 8001  # Container Port
    nodePort: 30001   # Node Port/Host Port
    protocol: TCP